//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turkcell_GY_Urun_Takip_Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbUrunEntities1 : DbContext
    {
        public DbUrunEntities1()
            : base("name=DbUrunEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAdmin> TBLAdmins { get; set; }
        public virtual DbSet<TBLKategori> TBLKategoris { get; set; }
        public virtual DbSet<TBLMusteri> TBLMusteris { get; set; }
        public virtual DbSet<TBLSatıslar> TBLSatıslar { get; set; }
        public virtual DbSet<TBLUrunler> TBLUrunlers { get; set; }
    }
}
