//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turkcell_GY_Urun_Takip_Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUrunler()
        {
            this.TBLSatıslar = new HashSet<TBLSatıslar>();
        }
    
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<short> Stok { get; set; }
        public Nullable<decimal> AlisFiyat { get; set; }
        public Nullable<decimal> SatisFiyati { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual TBLKategori TBLKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSatıslar> TBLSatıslar { get; set; }
    }
}
